### ISSUE TITLE
DTU_aug_masks

### ISSUE THREAD

**Issue by Leroy0709** [ewrfcas/MVSFormer#12]
请问这个
  File "/root/MVSFormer/datasets/dtu_dataset_ms.py", line 310, in __getitem__
    img_, depth_hr_, intrinsics_, depth_mask_hr_, offset_y, offset_x = self.final_crop(img, depth_hr, intrinsics, depth_mask_hr,
  File "/root/MVSFormer/datasets/dtu_dataset_ms.py", line 226, in final_crop
    offset_y = random.randint(0, h - crop_h)
  File "/root/miniconda3/lib/python3.8/random.py", line 248, in randint
    return self.randrange(a, b+1)
  File "/root/miniconda3/lib/python3.8/random.py", line 226, in randrange
    raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0, -558, -558)
这里报错该怎么更改设置呢？

**Comment by ewrfcas** [comment]
你好，mask是没有用到的。

**Comment by ewrfcas** [comment]
> 请问这个 File "/root/MVSFormer/datasets/dtu_dataset_ms.py", line 310, in **getitem** img_, depth_hr_, intrinsics_, depth_mask_hr_, offset_y, offset_x = self.final_crop(img, depth_hr, intrinsics, depth_mask_hr, File "/root/MVSFormer/datasets/dtu_dataset_ms.py", line 226, in final_crop offset_y = random.randint(0, h - crop_h) File "/root/miniconda3/lib/python3.8/random.py", line 248, in randint return self.randrange(a, b+1) File "/root/miniconda3/lib/python3.8/random.py", line 226, in randrange raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width)) ValueError: empty range for randrange() (0, -558, -558) 这里报错该怎么更改设置呢？

这个似乎是使用了其他数据集训练 ，或者错改了image size setting?

**Comment by McCartney2** [comment]
请问outdir在OneDrive的预训练模型里有吗？

**Comment by McCartney2** [comment]
Traceback (most recent call last):
  File "test.py", line 580, in <module>
    save_depth(testlist, config)
  File "test.py", line 203, in save_depth
    checkpoint = torch.load(config.resume)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
这一步还是测试机dtu有问题吗？

**Comment by McCartney2** [comment]
Traceback (most recent call last):
  File "test.py", line 580, in <module>
    save_depth(testlist, config)
  File "test.py", line 203, in save_depth
    checkpoint = torch.load(config.resume)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
这一步是测试集dtu出问题了吗？

**Comment by McCartney2** [comment]
会不会是因为这里面的put_pretrained_models_here显示的是0 bytes导致的

**Comment by ewrfcas** [comment]
> Traceback (most recent call last): File "test.py", line 580, in save_depth(testlist, config) File "test.py", line 203, in save_depth checkpoint = torch.load(config.resume) File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 608, in load return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args) File "/root/miniconda3/lib/python3.8/site-packages/torch/serialization.py", line 777, in _legacy_load magic_number = pickle_module.load(f, **pickle_load_args) EOFError: Ran out of input 这一步是测试集dtu出问题了吗？

似乎是加载权重出问题了

**Comment by McCartney2** [comment]
0
processing /root/autodl-tmp/OUTPUT1/Francis, ref-view299, photo/geo/final-mask:0.0441698282957077/0.03618212044239044/0.03239171952009201
0
processing /root/autodl-tmp/OUTPUT1/Francis, ref-view300, photo/geo/final-mask:0.04675532504916191/0.0370481014251709/0.032665058970451355
0
processing /root/autodl-tmp/OUTPUT1/Francis, ref-view301, photo/geo/final-mask:0.04574046656489372/0.038646504282951355/0.034036554396152496
Write combined PCD
Killed
我这突然终止了  显存不够了吗？感觉不像

**Comment by McCartney2** [comment]
processing /root/autodl-tmp/OUTPUT2/Temple, ref-view96, photo/geo/final-mask:0.08137015998363495/4.78707136153389e-07/0.0
Traceback (most recent call last):
  File "test.py", line 585, in <module>
    pcd_filter(testlist)
  File "test.py", line 560, in pcd_filter
    pcd_filter_worker(scan)
  File "test.py", line 555, in pcd_filter_worker
    dynamic_filter_depth(pair_folder, scan_folder, out_folder, os.path.join(args.outdir, save_name))
  File "test.py", line 497, in dynamic_filter_depth
    reproj_depth[~vis_mask.squeeze(2)] = 1  # [n v h w ]
IndexError: too many indices for tensor of dimension 4
请问这个是因为显存不够吗？

**Comment by maybeLx** [comment]
你这个应该是代码跑的有问题，这里跑的是reprojection， 一个是confidence 大于某一个阈值，另一个则是 冲投影误差小于某个阈值，但是这里的的mask很低，应该是哪儿跑的有问题。

**Comment by maybeLx** [comment]
> processing /root/autodl-tmp/OUTPUT2/Temple, ref-view96, photo/geo/final-mask:0.08137015998363495/4.78707136153389e-07/0.0 Traceback (most recent call last): File "test.py", line 585, in pcd_filter(testlist) File "test.py", line 560, in pcd_filter pcd_filter_worker(scan) File "test.py", line 555, in pcd_filter_worker dynamic_filter_depth(pair_folder, scan_folder, out_folder, os.path.join(args.outdir, save_name)) File "test.py", line 497, in dynamic_filter_depth reproj_depth[~vis_mask.squeeze(2)] = 1 # [n v h w ] IndexError: too many indices for tensor of dimension 4 请问这个是因为显存不够吗？
你这个应该是代码跑的有问题，这里跑的是reprojection， 一个是confidence 大于某一个阈值，另一个则是 冲投影误差小于某个阈值，但是这里的的mask很低，应该是哪儿跑的有问题。

**Comment by maybeLx** [comment]
> processing /root/autodl-tmp/OUTPUT2/Temple, ref-view96, photo/geo/final-mask:0.08137015998363495/4.78707136153389e-07/0.0 Traceback (most recent call last): File "test.py", line 585, in pcd_filter(testlist) File "test.py", line 560, in pcd_filter pcd_filter_worker(scan) File "test.py", line 555, in pcd_filter_worker dynamic_filter_depth(pair_folder, scan_folder, out_folder, os.path.join(args.outdir, save_name)) File "test.py", line 497, in dynamic_filter_depth reproj_depth[~vis_mask.squeeze(2)] = 1 # [n v h w ] IndexError: too many indices for tensor of dimension 4 请问这个是因为显存不够吗？

你这个应该是代码跑的有问题，这里跑的是reprojection， 一个是confidence 大于某一个阈值，另一个则是 冲投影误差小于某个阈值，但是这里的的mask很低，应该是哪儿跑的有问题。

**Comment by omnipotenttom** [comment]
> > 请问这个 File "/root/MVSFormer/datasets/dtu_dataset_ms.py", line 310, in **getitem** img_, depth_hr_, intrinsics_, depth_mask_hr_, offset_y, offset_x = self.final_crop(img, depth_hr, intrinsics, depth_mask_hr, File "/root/MVSFormer/datasets/dtu_dataset_ms.py", line 226, in final_crop offset_y = random.randint(0, h - crop_h) File "/root/miniconda3/lib/python3.8/random.py", line 248, in randint return self.randrange(a, b+1) File "/root/miniconda3/lib/python3.8/random.py", line 226, in randrange raise ValueError("empty range for randrange() (%d, %d, %d)" % (istart, istop, width)) ValueError: empty range for randrange() (0, -558, -558) 这里报错该怎么更改设置呢？
> 
> 这个似乎是使用了其他数据集训练 ，或者错改了image size setting?
作者您好，非常感谢您的工作！我遇到了一样的问题，我在使用dtu数据集时将您提供的Depths_raw解压到了原始的dtu数据集中然后开始运行代码![image](https://github.com/user-attachments/assets/0e46151f-811e-4fe1-85f6-f5852442b5a5)，结果
![image](https://github.com/user-attachments/assets/24183008-f9ec-4459-9931-0e417e900671)
